package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemDO;
import com.miaoshaproject.dataobject.ItemDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    long countByExample(ItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    int deleteByExample(ItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */

    List<ItemDO> listItem();

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    List<ItemDO> selectByExample(ItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemDO record, @Param("example") ItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    int updateByExample(@Param("record") ItemDO record, @Param("example") ItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon May 20 15:43:16 CST 2019
     */
    int updateByPrimaryKey(ItemDO record);
    int increaseSales(@Param("id")Integer id, @Param("amount")Integer amount);
}