package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.PromoDO;
import com.miaoshaproject.dataobject.PromoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    long countByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    int deleteByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    List<PromoDO> selectByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    PromoDO selectByPrimaryKey(Integer id);

    PromoDO selecByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") PromoDO record, @Param("example") PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    int updateByExample(@Param("record") PromoDO record, @Param("example") PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue May 21 18:57:41 CST 2019
     */
    int updateByPrimaryKey(PromoDO record);
}